### ISSUE TITLE
Renomear org para dev-pp

### ISSUE THREAD

**Issue by joaocunha** [dev-pp/meetup#1]
Acredito que a organização como `dev-pp` fica mais "reutilizável". Nossa iniciativa pode se tornar mais que meetups.

Org: `dev-pp`
Esse repo: `meetup`

`github.com/dev-pp/meetup`
`github.com/dev-pp/site`
etc.

O que acham?

**Comment by felipeblini** [comment]
boa, eu e o Renan iamos colocar devpp mas já tinhan e nao pensamos em dev-pp

**Comment by felipeblini** [comment]
Done
